### ISSUE TITLE
Feature request: Bulk downloads

### ISSUE THREAD

**Issue by diamondavocado** [Belphemur/AddictedProxy#142]
Great job on this project; it's great. It deserves way more attention!

It would be amazing if you could add a bulk-download feature where you could download the subtitles for every episode (or every season!) of a show at once.

It would save people dozens (hundreds?) of manual clicks.

Ideally it would be smart enough to auto-group by release type, e.g. search for "Sopranos", bulk-download all English "HDTV" subtitles.

**Comment by Belphemur** [comment]
Hello,

I'm surprised you found the repo, I admit not publishing this info on the website :)

I would suggest to use [Bazarr](https://www.bazarr.media/) to manage your subtitle, with [Sonarr](https://sonarr.tv/) to take care of your shows.

The service is supported by Bazarr which will take care of checking for subtitles and download them, you'll find it under "Gestdown".

Now about your request to group subtitle, it's not that easy. Since the "release" is filled in by the uploader of the subtitle on Addic7ed, there isn't a clear pattern.

Sometimes they put "HDTV", "AMZ-HDTV", "AMZ.HD", etc ... You can see that with the Season 6 of the Show Outlander.

**Comment by diamondavocado** [comment]
@Belphemur Thank you for adding this feature! 🥳
